# Generated by Django 5.2.7 on 2025-11-06 16:30

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CVUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='My CV', max_length=200)),
                ('cv_file', cloudinary.models.CloudinaryField(max_length=255, verbose_name='cv')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Only one CV can be active at a time')),
            ],
            options={
                'verbose_name': 'CV Upload',
                'verbose_name_plural': 'CV Uploads',
                'ordering': ['-updated_at'],
            },
        ),
    ]
