# Generated by Django 5.2.7 on 2025-11-06 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_upload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvupload',
            name='cv_file',
            field=models.FileField(blank=True, null=True, upload_to='cv_files/'),
        ),
    ]
