# Generated by Django 5.2.7 on 2025-10-26 11:46

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_alter_herosection_image_alter_herosection_video_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mediafile',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Media File', 'verbose_name_plural': 'Media Files'},
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='icon',
            field=models.CharField(choices=[('Phone', 'Phone'), ('Mail', 'Mail'), ('MapPin', 'MapPin'), ('Clock', 'Clock')], help_text='Select an icon to represent the contact method', max_length=50),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='info',
            field=models.CharField(help_text='The actual contact information (e.g., example@email.com)', max_length=200),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Show or hide this contact info item'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='link',
            field=models.URLField(blank=True, help_text='Optional link (e.g., mailto:, tel:, or map link)', max_length=500),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Display order (lower numbers appear first)'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='title',
            field=models.CharField(help_text="Label for the contact info (e.g., 'Email Us')", max_length=100),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Internal notes for admins (not shown to users)'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='email',
            field=models.EmailField(help_text='Email address of the sender', max_length=254),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='is_read',
            field=models.BooleanField(default=False, help_text='Mark as read after viewing in admin'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='message',
            field=models.TextField(help_text='Message content'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='name',
            field=models.CharField(help_text='Name of the sender', max_length=100),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='replied',
            field=models.BooleanField(default=False, help_text='Mark if you have replied to this message'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='subject',
            field=models.CharField(help_text='Message subject', max_length=200),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='whatsapp',
            field=models.CharField(blank=True, help_text='Optional WhatsApp number', max_length=20),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='badge_icon',
            field=models.CharField(blank=True, help_text='Icon for the badge (e.g., MessageSquare, Award)', max_length=50),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='badge_text',
            field=models.CharField(blank=True, help_text='Small text badge (optional)', max_length=100),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='description',
            field=models.TextField(blank=True, help_text='Optional longer text for the hero section'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Upload background image', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Show or hide this hero section on the assigned page'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='page',
            field=models.CharField(choices=[('contact', 'Contact Page'), ('services', 'Services Page'), ('home', 'Home Page'), ('about', 'About Page')], help_text='Assign this hero section to a specific page', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='subtitle',
            field=models.TextField(help_text='Short description or subtitle'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='title',
            field=models.CharField(help_text='Main heading text for the hero section', max_length=200),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='video',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Upload background video', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='file',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Upload any media file (image, video, etc.)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='whychooseus',
            name='description',
            field=models.TextField(help_text='Short description of why clients should choose you'),
        ),
        migrations.AlterField(
            model_name='whychooseus',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Show or hide this item on the website'),
        ),
        migrations.AlterField(
            model_name='whychooseus',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Display order (lower numbers appear first)'),
        ),
        migrations.AlterField(
            model_name='whychooseus',
            name='title',
            field=models.CharField(help_text="Heading for this feature (e.g., 'Award Winning Team')", max_length=100),
        ),
    ]
