# Generated by Django 5.2.7 on 2025-11-01 02:51

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', cloudinary.models.CloudinaryField(blank=True, help_text='Upload your site logo (recommended size: 200x60px)', max_length=255, null=True, verbose_name='logo')),
                ('site_name', models.CharField(default='Alex Rodriguez', help_text='Name displayed if no logo is uploaded', max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Configuration',
                'verbose_name_plural': 'Site Configuration',
            },
        ),
    ]
