# Generated by Django 5.2.7 on 2025-10-22 08:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeCTA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g., Ready to Start Your Project?', max_length=200)),
                ('description', models.TextField(help_text='Description for the CTA section')),
                ('button_text', models.CharField(default='Contact Me', help_text='Text for the CTA button', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Display this CTA on the website')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Home CTA',
                'verbose_name_plural': 'Home CTAs',
            },
        ),
        migrations.CreateModel(
            name='HomeFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(help_text='e.g., What working hours are manageable for you?', max_length=200)),
                ('answer', models.TextField(help_text='Answer to the FAQ')),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('is_active', models.BooleanField(default=True, help_text='Display this FAQ on the website')),
            ],
            options={
                'verbose_name': 'Home FAQ',
                'verbose_name_plural': 'Home FAQs',
                'ordering': ['order', 'question'],
            },
        ),
        migrations.CreateModel(
            name='HomeHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Main title for the hero section', max_length=200)),
                ('typewriter_phrases', models.TextField(help_text='Comma-separated phrases for typewriter effect (e.g., Cinematic Excellence,Visual Storytelling)')),
                ('subtitle', models.TextField(help_text='Subtitle or description for the hero section')),
                ('video', models.FileField(help_text='Upload hero section video (MP4, WebM, or MOV format)', upload_to='home_hero_videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'mov'])])),
                ('primary_button_text', models.CharField(default='Watch Portfolio Reel', help_text='Text for the primary button', max_length=100)),
                ('secondary_button_text', models.CharField(default='View Our Work', help_text='Text for the secondary button', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Display this hero content on the website')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Home Hero',
                'verbose_name_plural': 'Home Hero Sections',
            },
        ),
        migrations.CreateModel(
            name='HomeIntro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Main title for the intro section', max_length=200)),
                ('subtitle', models.TextField(help_text='Subtitle or description for the intro section')),
                ('image', models.ImageField(help_text='Image for the intro section (JPG, JPEG, or PNG format)', upload_to='home_intro_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])])),
                ('achievements', models.TextField(help_text='Comma-separated list of recent achievements (e.g., Vimeo Staff Pick Winner 2023,Wedding Wire Couples Choice Award)')),
                ('primary_button_text', models.CharField(default='View My Portfolio', help_text='Text for the primary button', max_length=100)),
                ('secondary_button_text', models.CharField(default='Contact Me', help_text='Text for the secondary button', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Display this intro content on the website')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Home Intro',
                'verbose_name_plural': 'Home Intro Sections',
            },
        ),
        migrations.CreateModel(
            name='HomeProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g., Creative Planning', max_length=100)),
                ('description', models.TextField(help_text='Description of the process step')),
                ('icon', models.CharField(choices=[('PenTool', 'PenTool'), ('Camera', 'Camera'), ('Edit3', 'Edit3')], default='PenTool', max_length=50)),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('is_active', models.BooleanField(default=True, help_text='Display this process step on the website')),
            ],
            options={
                'verbose_name': 'Home Process',
                'verbose_name_plural': 'Home Processes',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='HomeService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g., Wedding Films', max_length=100)),
                ('description', models.TextField(help_text='Description of the service')),
                ('icon', models.CharField(choices=[('Film', 'Film'), ('Play', 'Play'), ('Award', 'Award')], default='Film', max_length=50)),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('is_active', models.BooleanField(default=True, help_text='Display this service on the website')),
            ],
            options={
                'verbose_name': 'Home Service',
                'verbose_name_plural': 'Home Services',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='HomeSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g., Storytelling', max_length=100)),
                ('description', models.TextField(help_text='Description of the skill')),
                ('icon', models.CharField(choices=[('PenTool', 'PenTool'), ('Palette', 'Palette'), ('Music', 'Music'), ('Cpu', 'Cpu'), ('MessageCircle', 'MessageCircle'), ('Edit3', 'Edit3')], default='PenTool', max_length=50)),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('is_active', models.BooleanField(default=True, help_text='Display this skill on the website')),
            ],
            options={
                'verbose_name': 'Home Skill',
                'verbose_name_plural': 'Home Skills',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='HomeStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Projects Completed', max_length=100)),
                ('value', models.IntegerField(default=0, help_text='Numeric value for the stat (e.g., 500)')),
                ('suffix', models.CharField(default='+', help_text="Suffix for the stat (e.g., '+')", max_length=10)),
                ('icon', models.CharField(choices=[('Calendar', 'Calendar'), ('Users', 'Users'), ('Award', 'Award'), ('MapPin', 'MapPin')], default='Calendar', max_length=50)),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('is_active', models.BooleanField(default=True, help_text='Display this stat on the website')),
            ],
            options={
                'verbose_name': 'Home Stat',
                'verbose_name_plural': 'Home Stats',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='HomeTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g., Software', max_length=100)),
                ('description', models.TextField(help_text='Description of the tool')),
                ('icon', models.CharField(choices=[('Laptop', 'Laptop'), ('Camera', 'Camera'), ('Workflow', 'Workflow'), ('Wifi', 'Wifi')], default='Laptop', max_length=50)),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('is_active', models.BooleanField(default=True, help_text='Display this tool on the website')),
            ],
            options={
                'verbose_name': 'Home Tool',
                'verbose_name_plural': 'Home Tools',
                'ordering': ['order', 'title'],
            },
        ),
    ]
