# Generated by Django 5.2.7 on 2025-10-26 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_homehero_video_alter_homeintro_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homecta',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Home CTA', 'verbose_name_plural': 'Home CTAs'},
        ),
        migrations.AlterModelOptions(
            name='homehero',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Home Hero', 'verbose_name_plural': 'Home Hero Sections'},
        ),
        migrations.AlterModelOptions(
            name='homeintro',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Home Intro', 'verbose_name_plural': 'Home Intro Sections'},
        ),
        migrations.AlterField(
            model_name='homefaq',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Display order (lower numbers appear first)'),
        ),
        migrations.AlterField(
            model_name='homehero',
            name='typewriter_phrases',
            field=models.TextField(help_text='Comma-separated phrases for typewriter effect (e.g., Cinematic Excellence, Visual Storytelling)'),
        ),
        migrations.AlterField(
            model_name='homeintro',
            name='achievements',
            field=models.TextField(help_text='Comma-separated list of recent achievements (e.g., Vimeo Staff Pick Winner 2023, Wedding Wire Couples Choice Award)'),
        ),
        migrations.AlterField(
            model_name='homeprocess',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Display order (lower numbers appear first)'),
        ),
        migrations.AlterField(
            model_name='homeservice',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Display order (lower numbers appear first)'),
        ),
        migrations.AlterField(
            model_name='homeskill',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Display order (lower numbers appear first)'),
        ),
        migrations.AlterField(
            model_name='homestat',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Display order (lower numbers appear first)'),
        ),
        migrations.AlterField(
            model_name='homestat',
            name='value',
            field=models.PositiveIntegerField(default=0, help_text='Numeric value for the stat (e.g., 500)'),
        ),
        migrations.AlterField(
            model_name='hometool',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Display order (lower numbers appear first)'),
        ),
    ]
