# Generated by Django 5.2.7 on 2025-11-05 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_homecta_options_alter_homehero_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homestat',
            name='suffix',
            field=models.CharField(default='', help_text="Suffix for the stat (optional, e.g., '+')", max_length=10),
        ),
        migrations.AlterField(
            model_name='homestat',
            name='value',
            field=models.CharField(help_text='Value for the stat (e.g., 500, 4M, 10K)', max_length=20),
        ),
    ]
