# Generated by Django 5.2.7 on 2025-11-18 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_homestat_suffix_alter_homestat_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homehero',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='home_hero_videos/'),
        ),
        migrations.AlterField(
            model_name='homeintro',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='home_intro_images/'),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='media_files/'),
        ),
    ]
