# Generated by Django 5.2.8 on 2025-11-19 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_homehero_video_alter_homeintro_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Name of the brand/client (for admin reference)', max_length=100)),
                ('logo', models.ImageField(help_text='Upload brand logo (preferably white/transparent PNG)', upload_to='home_logos/')),
                ('website_url', models.URLField(blank=True, help_text="Optional link to client's website", null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower = appears first)')),
                ('is_active', models.BooleanField(default=True, help_text='Show this logo on homepage carousel')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Home Logo',
                'verbose_name_plural': 'Home Logos',
                'ordering': ['order', 'title'],
            },
        ),
    ]
