# Generated by Django 5.2.8 on 2025-11-19 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_homelogo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Client's full name", max_length=100)),
                ('role', models.CharField(help_text='e.g., CEO, Bride, Marketing Director', max_length=100)),
                ('company', models.CharField(help_text='Company or event name', max_length=150)),
                ('text', models.TextField(help_text='The testimonial quote')),
                ('rating', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5, help_text='Star rating (1-5)')),
                ('avatar', models.CharField(blank=True, help_text='Fallback initials (e.g., JD). Leave blank to use first letter of name.', max_length=2)),
                ('avatar_image', models.ImageField(blank=True, help_text='Optional profile photo', null=True, upload_to='testimonials/avatars/')),
                ('gradient_color', models.CharField(default='from-purple-500 to-pink-500', help_text='Tailwind gradient class (e.g., from-purple-600 to-blue-600)', max_length=100)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower = first)')),
                ('is_active', models.BooleanField(default=True, help_text='Show on homepage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
