# Generated by Django 5.2.7 on 2025-10-28 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_mediafile_file_alter_portfoliohero_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfoliohero',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['order', '-created_at']},
        ),
        migrations.AlterField(
            model_name='project',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='technologies',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
