# Generated by Django 5.2.7 on 2025-10-21 17:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='abouttabcontent',
            name='image',
            field=models.ImageField(blank=True, help_text='Image for the tab (JPG, JPEG, or PNG format)', null=True, upload_to='about_tab_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
    ]
