# Generated by Django 5.2.7 on 2025-10-26 11:46

import cloudinary.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_alter_abouthero_video_alter_abouttabcontent_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mediafile',
            options={'verbose_name': 'Media File', 'verbose_name_plural': 'Media Files'},
        ),
        migrations.AlterField(
            model_name='abouthero',
            name='video',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Upload hero section background video', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='abouttabcontent',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Upload tab image', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='corevalue',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Display order (lower numbers appear first)'),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='file',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Upload any media file (image, video, etc.)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='level',
            field=models.PositiveIntegerField(help_text='Skill level as a percentage (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='skill',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Display order (lower numbers appear first)'),
        ),
        migrations.AlterField(
            model_name='stat',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Display order (lower numbers appear first)'),
        ),
        migrations.AlterField(
            model_name='stat',
            name='value',
            field=models.PositiveIntegerField(default=0, help_text='Numeric value for the stat (e.g., 500)'),
        ),
        migrations.AlterField(
            model_name='timelineevent',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Display order (lower numbers appear first)'),
        ),
    ]
