# Generated by Django 5.2.7 on 2025-11-05 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_alter_mediafile_options_alter_abouthero_video_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stat',
            name='suffix',
            field=models.CharField(default='', help_text="Optional suffix for the stat (e.g., '+')", max_length=10),
        ),
        migrations.AlterField(
            model_name='stat',
            name='value',
            field=models.CharField(help_text="Value for the stat (e.g., '4M', '500+')", max_length=20),
        ),
    ]
