# Generated by Django 5.2.7 on 2025-11-06 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0006_alter_stat_suffix_alter_stat_value'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutHero',
        ),
        migrations.AlterField(
            model_name='abouttabcontent',
            name='tab_name',
            field=models.CharField(choices=[('story', 'Story'), ('process', 'Process'), ('philosophy', 'Philosophy')], help_text='Name of the tab (Story, Philosophy, or Approach)', max_length=50, unique=True),
        ),
    ]
