# Generated by Django 5.2.7 on 2025-11-06 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0007_delete_abouthero_alter_abouttabcontent_tab_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abouttabcontent',
            name='tab_name',
            field=models.CharField(choices=[('story', 'Story'), ('process', 'Process'), ('philosophy', 'Philosophy')], help_text='Name of the tab (Story, Philosophy, or Process)', max_length=50, unique=True),
        ),
    ]
