# Generated by Django 5.2.7 on 2025-11-06 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0008_alter_abouttabcontent_tab_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corevalue',
            name='icon',
            field=models.CharField(choices=[('Film', 'Film - Creative Precision'), ('Users', 'Users - Clarity in Collaboration'), ('Heart', 'Heart - Calm Problem-Solving'), ('Lightbulb', 'Lightbulb - Growth-Driven Mindset')], default='Heart', max_length=50),
        ),
        migrations.AlterField(
            model_name='corevalue',
            name='title',
            field=models.CharField(help_text='e.g., Creative Precision', max_length=100),
        ),
    ]
