# Generated by Django 5.2.7 on 2025-11-18 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0009_alter_corevalue_icon_alter_corevalue_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abouttabcontent',
            name='content',
            field=models.TextField(help_text='Content for the tab, supports multiple paragraphs'),
        ),
        migrations.AlterField(
            model_name='abouttabcontent',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload tab image', null=True, upload_to='about_tabs/'),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='file',
            field=models.FileField(blank=True, help_text='Upload any media file (image, video, etc.)', null=True, upload_to='uploads/'),
        ),
    ]
