# Generated by Django 5.2.7 on 2025-10-21 10:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Wedding, Real Estate', max_length=100)),
                ('icon', models.CharField(choices=[('Sparkles', 'Sparkles'), ('Heart', 'Heart'), ('Building2', 'Building2'), ('MessageCircle', 'MessageCircle'), ('Film', 'Film')], default='Sparkles', max_length=50)),
                ('count', models.IntegerField(default=0, help_text='Number of projects in this category')),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('is_active', models.BooleanField(default=True, help_text='Display this category on the website')),
            ],
            options={
                'verbose_name': 'Portfolio Category',
                'verbose_name_plural': 'Portfolio Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Upload hero slide image', upload_to='hero_slides/')),
                ('video', models.FileField(help_text='Upload hero slide video (MP4, WebM, or MOV format)', upload_to='hero_videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'mov'])])),
                ('title', models.CharField(max_length=100)),
                ('views', models.CharField(default='0', help_text='e.g., 25K', max_length=10)),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('is_active', models.BooleanField(default=True, help_text='Display this slide on the website')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.portfoliocategory')),
            ],
            options={
                'verbose_name': 'Hero Slide',
                'verbose_name_plural': 'Hero Slides',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('thumbnail', models.ImageField(help_text='Upload project thumbnail image', upload_to='project_thumbnails/')),
                ('video', models.FileField(help_text='Upload project video (MP4, WebM, or MOV format)', upload_to='project_videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'mov'])])),
                ('description', models.TextField(help_text='Project description')),
                ('views', models.CharField(default='0', help_text='e.g., 12.5K', max_length=10)),
                ('likes', models.CharField(default='0', help_text='e.g., 2.1K', max_length=10)),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('is_active', models.BooleanField(default=True, help_text='Display this project on the website')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='portfolio.portfoliocategory')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['order', 'title'],
            },
        ),
    ]
