# Generated by Django 5.2.8 on 2025-11-18 17:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Client's full name", max_length=100)),
                ('role', models.CharField(help_text='e.g. Startup Founder, Wedding Client', max_length=100)),
                ('company', models.CharField(help_text='Company or event name', max_length=150)),
                ('text', models.TextField(help_text='The testimonial quote')),
                ('rating', models.PositiveSmallIntegerField(default=5, help_text='Rating from 1 to 5 stars', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('avatar_image', models.ImageField(blank=True, help_text='Optional client photo (falls back to initials)', null=True, upload_to='testimonials/avatars/')),
                ('avatar_initials', models.CharField(blank=True, editable=False, max_length=3)),
                ('gradient_color', models.CharField(default='from-indigo-500 to-purple-500', help_text='Tailwind gradient (e.g. from-indigo-500 to-purple-500)', max_length=100)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower = first)')),
                ('is_active', models.BooleanField(default=True, help_text='Show on website?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
