# Generated by Django 5.2.8 on 2025-11-18 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testimonial',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'Testimonial', 'verbose_name_plural': 'Testimonials'},
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='avatar_image',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='avatar_initials',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='testimonial',
            name='avatar',
            field=models.CharField(blank=True, help_text='e.g. JD', max_length=10),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='avatar_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='company',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='gradient_color',
            field=models.CharField(default='from-purple-500 to-pink-500', help_text='Tailwind gradient classes, e.g. from-blue-500 to-cyan-500', max_length=100),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='rating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5, help_text='Rating from 1 to 5 stars'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='role',
            field=models.CharField(help_text='e.g., Wedding Couple, Real Estate Agent', max_length=100),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='text',
            field=models.TextField(help_text='Testimonial content'),
        ),
    ]
