# Generated by Django 5.2.8 on 2025-11-18 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0002_alter_testimonial_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='is_from_new_app',
            field=models.BooleanField(default=True),
        ),
    ]
