# Generated by Django 5.2.8 on 2025-11-18 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0003_testimonial_is_from_new_app'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='avatar_url',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='company',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='gradient_color',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='is_from_new_app',
        ),
    ]
